# Generated by Django 5.0.2 on 2024-06-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'В обработке'), ('2', 'В доставке'), ('3', 'Оформлен')], default=('1', 'В обработке'), max_length=50, verbose_name='Статус заказа'),
        ),
    ]
